services:
  - type: web
    name: farmers-market-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: FLASK_ENV
        value: production
      - key: EMAIL_HOST
        sync: false # Set manually in Render dashboard
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_SECURE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false 